; tiles.asm
;
; Tile Source File.
;
; Info:
;   Section              : tiles ROMX
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : Byte-count as Constant.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 7
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "tiles", ROMX

; Start of tile array.
tile_data::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$FF,$FF,$FF,$49,$36,$C9
DB $89,$52,$00,$91,$00,$00,$00,$00
DB $00,$00,$81,$81,$81,$01,$00,$81
DB $81,$00,$00,$81,$00,$00,$00,$00
DB $3C,$3C,$7E,$7C,$FF,$FE,$FF,$FE
DB $FF,$FC,$FF,$F8,$7E,$70,$3C,$00
DB $02,$C3,$40,$C3,$00,$E1,$60,$E7
DB $06,$F7,$81,$0E,$81,$00,$81,$00
DB $00,$00,$18,$18,$3C,$2C,$7E,$50
DB $1E,$2A,$04,$18,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$03,$07
DB $07,$0F,$4E,$3E,$BE,$34,$24,$36
DB $00,$00,$08,$08,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$10,$10,$00,$00
DB $00,$C0,$40,$C0,$00,$E0,$20,$A0
DB $00,$F0,$80,$00,$82,$02,$80,$02
DB $02,$03,$00,$03,$06,$07,$00,$07
DB $08,$09,$01,$0E,$01,$00,$01,$00
DB $00,$00,$20,$20,$00,$28,$02,$12
DB $10,$1A,$00,$2C,$00,$08,$00,$1C
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
; End of tiles.asm
